name: "merge-to-dev"

on:
  push:
    branches-ignore:
      - master
      - dev
    paths-ignore:
      #      - '.github/**'
      - '.husky/**'
      - '**.md'

jobs:
  merge-to-dev:
    name: Test before feature branch gets merged to dev
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      #          cache: 'npm'

      - name: Install npm dependencies
        run: npm clean-install

      - name: Lint code
        run: npm run lint

      - name: Lint dicts
        run: npm run lint:dict

      - name: Build Nest.js app
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Run end-to-end tests
        run: npm run test:e2e
